=== tamer1an/BackbonePolymerMix/raml-api/example_raml/schemas/user.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://jsonschema.net",
    "type": "object",
    "properties": {
        "id": {
            "id": "http://jsonschema.net/id",
            "type": "string"
        },
        "birthDate": {
            "id": "http://jsonschema.net/birthDate",
            "type": "string"
        },
        "email": {
            "id": "http://jsonschema.net/email",
            "type": "string"
        },
        "firstName": {
            "id": "http://jsonschema.net/firstName",
            "type": "string"
        },
        "lastName": {
            "id": "http://jsonschema.net/lastName",
            "type": "string"
        },
        "gender": {
            "id": "http://jsonschema.net/gender",
            "type": "string"
        },
        "status": {
            "id": "http://jsonschema.net/status",
            "type": "boolean"
        },
        "createdAt": {
            "id": "http://jsonschema.net/createdAt",
            "type": "string"
        },
        "updatedAt": {
            "id": "http://jsonschema.net/updatedAt",
            "type": "string"
        },
        "idArray": {
            "id": "http://jsonschema.net/idArray",
            "type": "array",
            "items": {
                "id": "http://jsonschema.net/idArray/0",
                "type": "string"
            }
        },
        "points": {
            "id": "http://jsonschema.net/points",
            "type": "integer"
        }
    }
}

=== tamer1an/BackbonePolymerMix/raml-api/example_raml/examples/user_post.json
{
    "birthDate": "1972-01-10",
    "email": "Coralie44@yahoo.com",
    "firstName": "Prince",
    "lastName": "Howe",
    "gender": "female",
    "status": false,
    "idArray": [
        "JDl2YtHcTrS5fJJS1MO9ti34",
        "moxAwY7so2sfvzQeoO1rwtmw",
        "1CovtdouoymhjuRvJYtXJE66"
    ],
    "points": 78
}

=== tamer1an/BackbonePolymerMix/raml-api/example_raml/examples/user.json
{
    "id": "5HEiCAt6kcE4XaeuMfVftPWJ",
    "birthDate": "1952-08-25",
    "email": "Verna_Emard0@gmail.com",
    "firstName": "Marion",
    "lastName": "Olson",
    "gender": "female",
    "status": true,
    "createdAt": "2015-07-30T05:59:12.979Z",
    "updatedAt": "2015-07-30T05:59:12.979Z",
    "idArray": [
        "bVqKk6qQgaH8w8vf2V9VhkdG",
        "2sMgk5cwjUDl1GCHalVvCjr7",
        "UsBRMTwFnjd8UxRQ41flGKXb",
        "VrF1BzaUlReChIDmHQCq3iGv",
        "p5C9LzLUZSVURB1l1JTbIlJ4",
        "sRG4bAhIoKl9Wy7XSTAYY1Xz",
        "21enB6WoDARHDtGaBy0soQ9h",
        "LKAjkvtIi4FQMl8qibAXQMMQ",
        "SBpbYcmlF4NvjlNsShlNuxVk"
    ],
    "points": 84
}
