=== tamer1an/BackbonePolymerMix/api-specs/prod-api-spec/schemas/bids.json
{
    "$schema": "http://json-schema.org",
    "id": "http://jsonschema.net",
    "type": "array",
    "items": {
        "id": "http://jsonschema.net/0",
        "type": "object",
        "properties": {
            "id": {
                "type" : "string"
            },
            "owner": {
                "type" : "string"
            },
            "roles" : {
                "type" : "string"
            },
            "name" : {
                "type" : "string"
            },
            "description" : {
                "type" : "string"
            },
            "startDate":  {
                "type" : "string"
            },
            "endDate": {
                "type" : "string"
            },
            "creationDate" : {
                "type" : "string"
            },
            "version" : {
                "type" : "string"
            }
        }
    }
}

=== tamer1an/BackbonePolymerMix/api-specs/prod-api-spec/examples/bid.json
{
    "id": "IH4aFVPJ4GgocNKRt3xho80V",
    "owner": "Hershel Ferry",
    "roles": "networks, systems",
    "name": "Leuschke - Runolfsson",
    "description": "zero defect",
    "startDate": "2014-10-26T03:13:12.221Z",
    "endDate": "2016-10-10T02:11:57.306Z",
    "creationDate": "2014-11-15T22:09:41.139Z",
    "version": "1.53"
}

=== tamer1an/BackbonePolymerMix/api-specs/prod-api-spec/examples/bids.json
[
    {
        "id": "wHLBqpOVljvo7CYyDAVrCARd",
        "owner": "Bella Bednar",
        "roles": "e-business, technologies",
        "name": "Satterfield, Spencer and Lockman",
        "description": "heuristic",
        "startDate": "2014-11-30T03:06:56.349Z",
        "endDate": "2016-06-13T15:21:45.336Z",
        "creationDate": "2015-02-04T17:37:30.861Z",
        "version": "1.72"
    },
    {
        "id": "gEWuem81wOVeF5f9f0i7G6Un",
        "owner": "Violet Bergnaum",
        "roles": "users, eyeballs",
        "name": "Corkery, Pacocha and Wuckert",
        "description": "multi-tasking",
        "startDate": "2015-04-19T23:33:06.097Z",
        "endDate": "2015-12-04T22:45:50.159Z",
        "creationDate": "2015-06-09T12:36:16.055Z",
        "version": "1.84"
    },
    {
        "id": "pQIYGhOT2qgjvzHWoIPPPvfw",
        "owner": "Noelia Kulas",
        "roles": "convergence, portals",
        "name": "Senger LLC",
        "description": "bifurcated",
        "startDate": "2015-09-09T20:09:54.955Z",
        "endDate": "2016-03-25T07:20:48.128Z",
        "creationDate": "2015-04-23T06:54:13.277Z",
        "version": "1.72"
    },
    {
        "id": "hWogZQSZeVXKDIcMixzqd5LT",
        "owner": "Ilene Schowalter",
        "roles": "web services, markets",
        "name": "Bergstrom LLC",
        "description": "secondary",
        "startDate": "2015-01-27T10:54:15.405Z",
        "endDate": "2016-01-31T06:13:42.785Z",
        "creationDate": "2014-11-04T23:06:45.579Z",
        "version": "1.40"
    },
    {
        "id": "Tk1fguAitWQz6EJhsSo746CV",
        "owner": "Braeden Hyatt",
        "roles": "platforms, networks",
        "name": "Hudson Inc",
        "description": "multimedia",
        "startDate": "2015-10-09T02:32:07.265Z",
        "endDate": "2016-06-15T14:04:41.948Z",
        "creationDate": "2015-02-02T18:05:49.783Z",
        "version": "1.83"
    },
    {
        "id": "gYAQkejoGuXWFc9LDf2ovnpS",
        "owner": "Luciano Pollich",
        "roles": "deliverables, ROI",
        "name": "Lebsack - Rogahn",
        "description": "multi-tasking",
        "startDate": "2015-03-09T10:38:13.867Z",
        "endDate": "2016-07-15T22:54:56.039Z",
        "creationDate": "2015-03-01T06:50:29.353Z",
        "version": "1.87"
    },
    {
        "id": "q9m2CIgybjy9c1gbfa1z2oE1",
        "owner": "Colby Bogisich",
        "roles": "eyeballs, e-services",
        "name": "McDermott - Yost",
        "description": "holistic",
        "startDate": "2015-07-15T01:53:29.336Z",
        "endDate": "2016-10-03T18:34:35.851Z",
        "creationDate": "2014-11-21T20:16:20.437Z",
        "version": "1.45"
    },
    {
        "id": "6TNt2AOa7dDqHrYdllJjXOCT",
        "owner": "Sienna Jakubowski",
        "roles": "vortals, bandwidth",
        "name": "Stoltenberg LLC",
        "description": "modular",
        "startDate": "2014-12-15T01:20:25.204Z",
        "endDate": "2015-11-03T01:18:15.980Z",
        "creationDate": "2015-03-09T15:55:40.031Z",
        "version": "1.13"
    },
    {
        "id": "YoxGmTu8dydtWsWAIOsLofff",
        "owner": "Jairo Abernathy",
        "roles": "methodologies, initiatives",
        "name": "Ebert, O'Connell and Gislason",
        "description": "disintermediate",
        "startDate": "2015-01-21T11:37:09.025Z",
        "endDate": "2016-08-10T09:06:02.602Z",
        "creationDate": "2015-08-24T20:59:03.937Z",
        "version": "1.22"
    },
    {
        "id": "C8Ymht8UJ84LNSXdTB4z31PC",
        "owner": "Era Ziemann",
        "roles": "vortals, methodologies",
        "name": "Dietrich, Adams and Walker",
        "description": "dynamic",
        "startDate": "2015-05-15T16:32:56.139Z",
        "endDate": "2015-10-26T04:08:39.659Z",
        "creationDate": "2014-11-09T07:39:44.311Z",
        "version": "1.30"
    },
    {
        "id": "IH4aFVPJ4GgocNKRt3xho80V",
        "owner": "Hershel Ferry",
        "roles": "networks, systems",
        "name": "Leuschke - Runolfsson",
        "description": "zero defect",
        "startDate": "2014-10-26T03:13:12.221Z",
        "endDate": "2016-10-10T02:11:57.306Z",
        "creationDate": "2014-11-15T22:09:41.139Z",
        "version": "1.53"
    }
]
