=== tamer1an/BackbonePolymerMix/api-specs/prod-api-spec/schemas/client_country.json
{
    "$schema": "http://json-schema.org",
    "id": "http://jsonschema.net",
    "type": "object",
    "items": {
        "id": "http://jsonschema.net/0",
        "type": "object",
        "properties": {
            "id": {
                "type" : "string"
            },

            "clientCountryId": {
                "type" : "string"
            },
            "clientCountryName" : {
                "type" : "string"
            },
            "clientCountryCode" : {
                "type" : "string"
            },
            "clientCurrencyId": {
                "type" : "string"
            },
            "clientCurrencyName" : {
                "type" : "string"
            },
            "clientCurrencyCode" : {
                "type" : "string"
            },

            "invoiceCountryId":  {
                "type" : "string"
            },
            "invoiceCountryName": {
                "type" : "string"
            },
            "invoiceCountryCode": {
                "type" : "string"
            },
            "invoiceCurrencyId" : {
                "type" : "string"
            },
            "invoiceCurrencyName" : {
                "type" : "string"
            },
            "invoiceCurrencyCode" : {
                "type" : "string"
            },

            "owningCountryId" : {
                "type" : "string"
            },
            "owningCountryName" : {
                "type" : "string"
            },
            "owningCountryCode" : {
                "type" : "string"
            },
            "owningCurrencyId" : {
                "type" : "string"
            },
            "owningCurrencyName" : {
                "type" : "string"
            },
            "owningCurrencyCode" : {
                "type" : "string"
            }
        }
    }
}

=== tamer1an/BackbonePolymerMix/api-specs/prod-api-spec/examples/client_country.json
{
    "id": "tD5H6mBGPlMYxWPfOCijXbPj",
    "clientCountryId": "nE85CT2CGFIjvF3h7hRskL3u",
    "clientCountryName": "Cambodia",
    "clientCountryCode": "GM",
    "clientCurrencyId": "FVJkgTpHvxWOqeiFOT0m28KV",
    "clientCurrencyName": "Kwanza",
    "clientCurrencyCode": "BGN",
    "invoiceCountryId": "XUPUC8Jfr0EzUCTi58fTAwBa",
    "invoiceCountryName": "Congo",
    "invoiceCountryCode": "GS",
    "invoiceCurrencyId": "geygAf8wpvluXexrP9SlVmCw",
    "invoiceCurrencyName": "Nuevo Sol",
    "invoiceCurrencyCode": "ERN",
    "owningCountryId": "Ggrgg93IkwJWuTrY7PnuPP1U",
    "owningCountryName": "Canada",
    "owningCountryCode": "JE",
    "owningCurrencyId": "YDBrB6Ds2szaFImfmh9nhrbF",
    "owningCurrencyName": "Saint Helena Pound",
    "owningCurrencyCode": "TTD"
}
